### ISSUE TITLE
Workaround for league client ewmh

### ISSUE THREAD

**Issue by Leixb** [jabuxas/configs#1]
I had the same issue with league client.

https://github.com/jabuxas/configs/blame/9926ea1f55e4e7d89bec982f86f7e80b06571764/desktop/configs/xmonad/src/main.hs#L53

I managed to work around it with this ugly hack, which you may find useful:

```haskell
myEwmhFullscreen :: XConfig a -> XConfig a
myEwmhFullscreen c =
  c
    { startupHook = startupHook c <+> fullscreenStartup,
      handleEventHook = handleEventHook c <+> fullscreenEventHookNoLeagueClient
    }

fullscreenEventHookNoLeagueClient :: Event -> X All
fullscreenEventHookNoLeagueClient ev@(ClientMessageEvent {ev_event_display = dpy, ev_window = win}) =
  liftIO (resClass <$> getClassHint dpy win) >>= \case
    "leagueclientux.exe" -> return $ All True
    _ -> fullscreenEventHook ev
```

Btw, thanks for pointing out that the cause was in `ewmhFullscreen`. This issue has been annoying me for quite a while now, until I found your config.

**Comment by jabuxas** [comment]
Hey, you're welcome hahaha. I was troubled with quite some things related to games at one time and decided to find the cause, because with the default config it worked ok.

The #450 and #452 refers to issues in xmonad's github I opened myself, not really sure if they're still open, don't think though it will ever get really fixed, the guys on IRC said something about if changing these things they would need to change the core of xmonad.

And thank you a lot, I'm not currently using xmonad because I've been trying out wayland, if I get tired of it I may come back to xmonad since it is the wm that I have the most affinity with, then I'll try out your hack :)
